version: '3'
services:
  db:
    build: ./db
    ports:
      - "5432:5432"
  backend:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000" #Debug port
      - "49401:49401"
      - "9999:9999"
    depends_on:
      - db
