version: '3'
services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - pgdevdata:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - imgsnodo:/home
    depends_on:
      - db
  frontend:
    build: ./front
    ports:
      - "80:80"
    volumes:
      - imgsnodo:/home:ro
    depends_on:
      - backend
volumes:
  imgsnodo:
  pgdevdata: