version: '3'
services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - pgdevdata:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
volumes:
  pgdevdata: